### ISSUE TITLE
Manual Search Crashes LazyLibrarian

### ISSUE THREAD

**Issue by PeteJB** [DobyTang/LazyLibrarian#1174]
Hi,

I have a problem with the manual search in LazyLibrarian. When I click on manual under a book, it opens a new tab (with nothing in it) and LazyLibrarian crashes and restarts.

I have pasted part of the log. The last message was at 17:02:54. I waited approximately 5 minutes before clicking on manual and the next message is at 17:08:15

To help with identifying and fixing issues, please include as much information as possible, including:
### LazyLibrarian version number (at the bottom of config page)
Current Version: 1c112dd92bfdc93fc1ae9abe4c4d01c38058227b

### Operating system used (windows, mac, linux, NAS type)
Alpine Linux. Running in a docker. 

### Interface in use (default, bookstrap)
bookstrap

### Which api (Goodreads, GoogleBooks, both)
Goodreads

### Source of your LazyLibrarian installation (git, zip file, 3rd party package)
Thraxis Docker: https://hub.docker.com/r/thraxis/lazylibrarian-calibre/

### Relevant debug log with api keys and any passwords redacted

08-Jan-2018 17:02:54 - DEBUG   :: MAIN : LazyLibrarian.py:main:163 : Current Version [1c112dd92bfdc93fc1ae9abe4c4d01c38058227b] - Latest remote version [b0f8c37401c1c88fc21c0e657c8a095346e7764c] - Install type [git]
08-Jan-2018 17:02:54 - INFO    :: MAIN : LazyLibrarian.py:main:198 : Starting LazyLibrarian on port: 5299, webroot ""
08-Jan-2018 17:02:54 - INFO    :: MAIN : webStart.py:initialize:59 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
08-Jan-2018 17:02:54 - DEBUG   :: MAIN : common.py:scheduleJob:292 : Start processDir job in 10 minutes
08-Jan-2018 17:02:54 - DEBUG   :: MAIN : common.py:scheduleJob:305 : Start search_book job in 360 minutes
08-Jan-2018 17:02:54 - DEBUG   :: MAIN : common.py:scheduleJob:299 : Start search_magazines job in 360 minutes
08-Jan-2018 17:02:54 - DEBUG   :: MAIN : common.py:scheduleJob:316 : Start checkForUpdates job in 24 hours
08-Jan-2018 17:02:54 - DEBUG   :: MAIN : common.py:scheduleJob:344 : Start authorUpdate job in 55 hours
08-Jan-2018 17:08:15 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1009 : getBookCover: Returning Cached response for /config/cache/book/97888.jpg
08-Jan-2018 17:08:21 - INFO    :: MAIN : __init__.py:initialize:555 : Log level set to [3]- Log Directory is [/config/log] - Config level is [3]
08-Jan-2018 17:08:21 - INFO    :: MAIN : __init__.py:initialize:557 : Screen Log set to EXTENDED DEBUG

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Seems to be crashing trying to get the book covers. In the manual edit page we try to collect a few different covers so we can give a choice of which to use. I will have a look at this later today, might need to add some more debugging messages to track progress through the various covers.

**Comment by PeteJB** [comment]
Great. Thanks for the help.

**Comment by philborman** [comment]
Just pushed a new version with some extra debugging to hopefully track this down

**Comment by PeteJB** [comment]
Thanks. I've requested the docker be updated to include the new level of code. Hopefully that will happen soon. If not, I will install a different docker that gets updated weekly.

I'll updated this issue with a new debug (hopefully within a week).

**Comment by philborman** [comment]
You should be able to upgrade the lazylibrarian version from inside the docker, there is a "check version" button on the lazylibrarian config page that will offer an upgrade if available, unless the docker creator has disabled it

**Comment by PeteJB** [comment]
Thanks, updated to the latest version: 
Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 7b736aa8db9d5b46c2c5744c0f9d7d0633377922 : Latest Version: 7b736aa8db9d5b46c2c5744c0f9d7d0633377922

1. Restarted LazyLibrarian and let it settle for about 10 minutes
2. Click on an author
3. In the title column, clicked on the word manual

Here is the results:
Note: 21:53 is the last log message before, after the restart and letting it sit.  22:02 is when I did steps 2 and 3 above. It looks like it started to get the bookcover and then LL restarted itself.


10-Jan-2018 21:53:58 - DEBUG :: MAIN : common.py:scheduleJob:316 : Start checkForUpdates job in 24 hours
10-Jan-2018 21:53:58 - DEBUG :: MAIN : common.py:scheduleJob:344 : Start authorUpdate job in 45 hours
10-Jan-2018 22:02:47 - DEBUG :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting current cover for 36553385
10-Jan-2018 22:02:47 - DEBUG :: EDIT_BOOK : bookwork.py:getBookCover:1014 : getBookCover: Returning Cached response for /config/cache/book/36553385.jpg
10-Jan-2018 22:02:47 - DEBUG :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting cover cover for 36553385
10-Jan-2018 22:02:47 - DEBUG :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting goodreads cover for 36553385
Lazylibrarian is starting up...
10-Jan-2018 22:02:54 - INFO :: MAIN : __init__.py:initialize:555 : Log level set to [3]- Log Directory is [/config/log] - Config level is [3]
10-Jan-2018 22:02:54 - INFO :: MAIN : __init__.py:initialize:557 : Screen Log set to EXTENDED DEBUG
10-Jan-2018 22:02:54 - DEBUG :: MAIN : __init__.py:check_setting:509 : Newznab0 : enabled -> True

**Comment by philborman** [comment]
ok so it looks like it gets stuck fetching a cover from goodreads. Fetches the first two ok. Doesn't seem to be crashing, just getting stuck.
I will have another look and see if I can see where the problem is. At least we've narrowed it down a bit...

**Comment by philborman** [comment]
I've just pushed an update, reorganised the cover creation. It's possible an invalid or missing goodreads link could have caused problems, added a few more debugging messages too.

**Comment by PeteJB** [comment]
Hi. Thanks for the update. Unfortunately it's still not working. Here's the latest log messages:

11-Jan-2018 18:38:37 - DEBUG   :: MAIN : versioncheck.py:logmsg:41 : Update check complete
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : LazyLibrarian.py:main:163 : Current Version [905ba68510f4b4f75f6ef5923192b00538c1b3d8] - Latest remote version [905ba68510f4b4f75f6ef5923192b00538c1b3d8] - Install type [git]
11-Jan-2018 18:38:37 - INFO    :: MAIN : LazyLibrarian.py:main:198 : Starting LazyLibrarian on port: 5299, webroot ""
11-Jan-2018 18:38:37 - INFO    :: MAIN : webStart.py:initialize:59 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : common.py:scheduleJob:292 : Start processDir job in 10 minutes
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : common.py:scheduleJob:305 : Start search_book job in 360 minutes
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : common.py:scheduleJob:299 : Start search_magazines job in 360 minutes
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : common.py:scheduleJob:316 : Start checkForUpdates job in 24 hours
11-Jan-2018 18:38:37 - DEBUG   :: MAIN : common.py:scheduleJob:344 : Start authorUpdate job in 45 hours
11-Jan-2018 18:48:31 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting current cover for 32075854
11-Jan-2018 18:48:31 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1014 : getBookCover: Returning Cached response for /config/cache/book/32075854.jpg
11-Jan-2018 18:48:31 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting cover cover for 32075854
11-Jan-2018 18:48:31 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1041 : getBookCover: No cover.jpg found for 32075854
11-Jan-2018 18:48:31 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting goodreads cover for 32075854
11-Jan-2018 18:48:36 - INFO    :: MAIN : __init__.py:initialize:555 : Log level set to [3]- Log Directory is [/config/log] - Config level is [3]
11-Jan-2018 18:48:36 - INFO    :: MAIN : __init__.py:initialize:557 : Screen Log set to EXTENDED DEBUG
11-Jan-2018 18:48:36 - DEBUG   :: MAIN : __init__.py:check_setting:509 : Newznab0 : enabled -> True

**Comment by philborman** [comment]
Still getting stuck inside the goodreads request. I'm struggling to see how/why.
Do you know how to log into your docker over ssh, and are you up for a little editing to try and find the problem?

**Comment by PeteJB** [comment]
Hi Phil,

No probs getting into the container. Not sure what editor is packaged with it, but I can always copy the file out, edit and copy it back in if I need. 

Thanks
Pete

**Comment by philborman** [comment]
Probably nano
Make sure you keep a copy of the unmodified original bookwork.py so you can put it back later.

All we need really are some checkpoints in the goodreads cover routine showing how far we get before it  gets stuck. That should show where the problem is, then it's a matter of working around it.
I've attached a new version of bookwork.py with the checkpoints already built in
Will be interesting to see the CHECKPOINT lines in the log

[bookwork.zip](https://github.com/DobyTang/LazyLibrarian/files/1622511/bookwork.zip)

**Comment by PeteJB** [comment]
Hi.

Latest log file below.

11-Jan-2018 23:55:55 - INFO    :: MAIN : webStart.py:initialize:59 : Starting LazyLibrarian web server on http://0.0.0.0:5299/
11-Jan-2018 23:56:15 - INFO    :: CONFIG_WRITE : __init__.py:config_write:991 : Config file [/config/config.ini] has been updated
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting current cover for 36553385
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1014 : getBookCover: Returning Cached response for /config/cache/book/36553385.jpg
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting cover cover for 36553385
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1041 : getBookCover: No cover.jpg found for 36553385
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1005 : Getting goodreads cover for 36553385
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1085 : CHECKPOINT 1, looking for bookid 36553385
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1091 : CHECKPOINT 2, found 3
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1093 : CHECKPOINT 3, booklink [https://www.goodreads.com/book/show/36553385-hari-and-his-electric-feet]
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1100 : CHECKPOINT 4, params ready
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1104 : CHECKPOINT 5, goodreads present in booklink
12-Jan-2018 00:00:19 - DEBUG   :: EDIT_BOOK : bookwork.py:getBookCover:1115 : CHECKPOINT 6, fetching url
12-Jan-2018 00:00:26 - INFO    :: MAIN : __init__.py:initialize:555 : Log level set to [3]- Log Directory is [/config/log] - Config level is [3]
12-Jan-2018 00:00:26 - INFO    :: MAIN : __init__.py:initialize:557 : Screen Log set to EXTENDED DEBUG
12-Jan-2018 00:00:26 - DEBUG   :: MAIN : __init__.py:check_setting:509 : Newznab0 : enabled -> True

**Comment by philborman** [comment]
Well that's interesting. We go off to fetch the URL and never return.
The URL [https://www.goodreads.com/book/show/36553385-hari-and-his-electric-feet] looks ok
so not sure what's going on. Do you have any warnings at startup about missing modules? Could be the python in your docker doesn't have ssl support, although I would have thought we should get an error back from fetching the url.
If you save the debug log from inside lazylibrarian log page it will create a file debug.zip. The first section of that file gives details on software versions installed, including the ssl stuff.

**Comment by PeteJB** [comment]
yep. will do a shutdown, clean startup and edit for passwords, api's etc and add here shortly

**Comment by philborman** [comment]
The inbuilt "save log" strips the passwords/api's for you ;-)

**Comment by PeteJB** [comment]
thanks..just found that out after wading through the file :)

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1622795/debug.zip)

**Comment by PeteJB** [comment]
Just clicked on the goodreads link for a book and it uses https and works ok

**Comment by philborman** [comment]
Yep, debug.log shows the ssl modules are all there. Even more interesting. What on earth can be going on?

You can replace the original bookwork.py file now, the problem seems to be in cache.py in the fetchURL routine.   Quite a simple debug line might help there, again keep a copy of the original.
line 42 says 
r = requests.get(URL, headers=headers, timeout=timeout, proxies=proxies)
Insert a new line below line 42
logger.debug("back from requests")
and a new line above line 42
logger.debug("[%s][%s][%s][%s]" % (URL, headers, timeout, proxies))

This will show us exactly what we sent to requests, and if/when we returned
Python is very fussy about whitespace, the new lines need to be vertically aligned with the "r" of "r = " using spaces to pad them out, not tabs. Should be 8 spaces each line.

**Comment by PeteJB** [comment]
Debug attached.
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1622889/debug.zip)

**Comment by philborman** [comment]
12-Jan-2018 01:07:12 - DEBUG   :: EDIT_BOOK : cache.py:fetchURL:42 : [https://www.goodreads.com/book/show/36553385-hari-and-his-electric-feet][{'User-Agent': 'LazyLibrarian (Linux 4.9.30-unRAID)'}][30][None]
12-Jan-2018 01:07:17 - INFO    :: MAIN : __init__.py:initialize:555 : Log level set to [3]- Log Directory is [/config/log] - Config level is [3]
12-Jan-2018 01:07:17 - INFO    :: MAIN : __init__.py:initialize:557 : Screen Log set to EXTENDED DEBUG

Not returning from requests, though your version of requests library is the same as the one I am using. URL looks fine, headers fine, timeout 30 seconds, no proxies.  The next log line is only 5 seconds later and looks like a complete lazylibrarian restart, so the call to requests is crashing the whole program.  Shouldn't really be possible, needs some thought. One more thing you could try, in __init__.pt line 1143 is a call to http://bootswatch.com/api/3.json  this is the first time we use requests in the program. Can you change that from http to https and see if you get the same problem there? In the last log you posted that was http and worked fine, would be interesting to see if it's https that's the problem, or only https with goodreads
Thanks for your help so far.

**Comment by PeteJB** [comment]
All good. Will need to try it tomorrow though (hope that's ok). Gotta get some sleep before work :(

**Comment by philborman** [comment]
No probs. I'm in Spain so it's mid afternoon here. I'm in no hurry, it's all working for me ;-)

**Comment by PeteJB** [comment]
Hi Phil,

I've changed the bootswatch to https:. I've added the debug log

Pete

[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1624481/debug.zip)

**Comment by philborman** [comment]
Well even more puzzling. The call to bootswatch using https works fine, still crashes when you try https to goodreads. I have no idea what's going on. I will grab the latest Thraxis docker here and try to reproduce the problem. If I can reproduce it I can probably fix it.  Any chance it's something like running out of memory? What are you running the docker on, in case that's relevant - and thanks for your help so far.

**Comment by PeteJB** [comment]
Hi. Don't think it's a memory problem. It's running on a server with 8GB Ram under Unraid.

I was thinking it might be a software level issue with a bug. I had a bit of a look today and I think it's running alpine 3.6 and an older(er) version of requests.py (but my knowledge of python was close to zero before I started this yesterday), so take my thoughts with a grain of salt. :)

**Comment by PeteJB** [comment]
I was thinking of downloading a different docker. The one I looked at was built with alpine 3.7 and giving that a try but didn't want to change this environment while you're debugging it. I'm happy to do it though if you think it would help. The other docker doesn't have calibredb support, so it's not my preferred one, but happy to do it if it helps.

**Comment by philborman** [comment]
I've downloaded the thraxis docker from the lazylibrarian front page and it's all working here.
It is alpine 3.6 but I just can't reproduce the problem at all. 
The requests library you are running is shipped with lazylibrarian in the lib directory, I don't think the docker includes it's own requests. we could upgrade the lazylibrarian requests library and see if that helps?

**Comment by philborman** [comment]
ok, so the thraxis docker does include requests, version 2.18.4 when we are shipping 2.12.4
might be worth trying the docker version instead, very easy to try...
in lazylibrarian/common.py line 30, change 
import lib.requests as requests
to
import requests

If that works I will do a "proper" fix later. Conditionally import system version and only local copy if there isn't a system one installed. Some nas systems don't include all the libraries we need.

**Comment by PeteJB** [comment]
Thanks for all your help. I'll try that now.

**Comment by PeteJB** [comment]
Still not working. I have attached the debug, but can confirm it's using requests version 2.18.4

But I have found something in the system log of unraid. Didn't think to look there. Anytime I do a request I get a python segfault.
Jan 13 00:23:59 Moose kernel: python[3758]: segfault at 2acc7d79fff8 ip 00002acc762b46c7 sp 00002acc7d7a0000 error 6 in libpython2.7.so.1.0[2acc76246000+342000]

Here's the debug anyway in case it's helpful. 
[debug.zip](https://github.com/DobyTang/LazyLibrarian/files/1626130/debug.zip)

**Comment by philborman** [comment]
ok, so it's not requests that's the problem per-se. Something in the python version or the kernel I guess?   
I don't suppose it will harm upgrading requests anyway.

**Comment by PeteJB** [comment]
Found a few posts around docker containers and their build. Don't understand a lot of what they are saying at the moment.
This post seems relevant -> https://github.com/docker-library/python/issues/211 and it points to the explanation in this one ->https://github.com/esnme/ultrajson/issues/254#issuecomment-314862445

**Comment by philborman** [comment]
ok, so it is running out of memory in the thread. The notes say alpine 3.7 fixes the problem so perhaps try that. I will send a message to Thraxis and see if he will update his build to Alpine 3.7

It shouldn't be too hard to add calibredb support to any other docker, I think it's just a matter of installing calibre from the main calibre site using their installer inside the docker, but I haven't actually tried it myself. For lazylibrarian we only need the calibredb program to be visible inside the docker, no external connections needed.

**Comment by PeteJB** [comment]
yep. Just installing the linuxserver docker now which has alpine 3.7. It'll take a while to read in the books etc, so might not get back to you until tomorrow

**Comment by PeteJB** [comment]
ok. Installed and doing the library scan now.

**Comment by philborman** [comment]
No problem. If you want to have a go at installing calibre in the new docker, it's in the old docker in /opt/calibre  I think you could probably just copy the whole directory over?

**Comment by PeteJB** [comment]
Hi. All good using the new docker with alpine 3.7. No lazylibrarian restarts or segfaults in unraid

**Comment by PeteJB** [comment]
No joy with installing calibre. Looks like it has some dependencies which are not in alpine linux. But that's fine, I think I can get away without calibredb. I'll just change my workflow a little bit to do some things manually with regards to calibre

**Comment by Thraxis** [comment]
My docker now uses Alpine 3.7 as of probably 18 hours ago or so.  

Clicking on "Manual" brings up the book edit screen for me with no issues

**Comment by philborman** [comment]
Excellent, great news, thanks for your fast work on this !!

**Comment by Thraxis** [comment]
And for reference.  I build the docker every friday for including any changes that have been added each week.

If I happen to notice a large number of changes before Friday (update notice in LL) I will sometimes fire off a re-build during the middle of the week.
