### ISSUE TITLE
LazyLibrarian Not Updating the Version

### ISSUE THREAD

**Issue by rutskiuk** [DobyTang/LazyLibrarian#1193]
Hi there,

I've run an update to pull through the latest version and it said I was 7 commits behind. 

Lazylibrarian Version: Master: b6a1158ade421e99189b386994fa373749106a83
Operating System: Windows 10
Interface: Default
Install Source: ZIP

I tried the trick of renaming version.txt and running the update again but that doesn't seem to create the version file any more:
Current Version: No Version File : Latest Version: 89141db37b490195a534c34c6f951c32e016140d

I have reinstated my version file and it now says I am 29 commits behind and when running the update it still says I am 29 commits behind.

I've looked at the logs for errors but nothing jumps out at me:

2018-01-15 20:54:30 | INFO | MAIN | versioncheck.py | logmsg | 39 | [VersionCheck] -  New version is available. You are 29 commits behind
-- | -- | -- | -- | -- | -- | --
2018-01-15 20:54:30 | DEBUG | MAIN | versioncheck.py | logmsg | 41 | (getCommitDifferenceFromGit) -  GitHub reports as follows Status [ahead] - Ahead [29] - Behind [0] - Total Commits [29]
2018-01-15 20:54:30 | DEBUG | MAIN | versioncheck.py | logmsg | 41 | pull total_commits from json object
2018-01-15 20:54:29 | DEBUG | MAIN | versioncheck.py | logmsg | 41 | (getCommitDifferenceFromGit)  -  Check for differences between local & repo by  [https://api.github.com/repos/dobytang/LazyLibrarian/compare/b6a1158ade421e99189b386994fa373749106a83...329cf3a03468a9a852c4d1222dfc85ef4b47bc4d]

Thanks in advance :)

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

### There is a built-in debug log creator on the logs page which makes it easy to provide this information
* To use it, first go to the log page and make sure debug logging is OFF
* Now press the "Start debug log" button
* Go and do whatever you need to recreate the error
* Go back to the log page and press "Save debug log"
* You can now turn debug logging off again if you want
* The saved log file will be found in your lazylibrarian log directory called debug.zip
* It will contain all lines logged since you pressed "Start debug log" with any passwords and api keys removed
* Attach the zip file to your bug report.

**Comment by philborman** [comment]
Unfortunately there was a bug in yesterdays release which is fixed now. I think if you grab the latest zip Latest commit 329cf3a  
it should hopefully be fixed.

**Comment by rutskiuk** [comment]
Just given that a go and it's still not creating a version file so says I'm running an unknown version. Should I create a version file and paste in the current build in?

**Comment by philborman** [comment]
Ah - there is a bug in the code setting the update signal, two equals signs instead of one so instead of setting the flag it just compares.
I will push an update later today. Just need to check if there are any other occurrences first.

**Comment by philborman** [comment]
Should be fixed now
