### ISSUE TITLE
Selecting magazine issues, and then the delete dropdown is NOT deleting.

### ISSUE THREAD

**Issue by MrMxyzptlk** [DobyTang/LazyLibrarian#1350]
Selecting magazine issues, and then the delete dropdown is NOT deleting.

The popup shows and says are you sure you would like to delete xxx amount of selected issues, but they don't delete after clicking OK, and the log shows nothing.

**Comment by philborman** [comment]
Fixed now, will push a new version tomorrow.

**Comment by MrMxyzptlk** [comment]
Thank you.

**Comment by MrMxyzptlk** [comment]
...just tried again, and LL is still not deleting the issues; nothing in the logs.

**Comment by philborman** [comment]
Ok thanks, It was fixed,  but I broke it again moving over to server-side processing.  Fixed again now, should push an update in the next hour or so.
