### ISSUE TITLE
Database Error: database is locked on fresh install

### ISSUE THREAD

**Issue by TommyE123** [DobyTang/LazyLibrarian#630]
On a fresh install the "Database Error: database is locked" files the log hangs Lazy Librarian. Restarting the service fixes the issue but this can't be done from the webpage as you can't get to the config page.
I suspect the solution to this issue is to either fix why its locking the database on the DB upgrade or perform a forced restart after its updated.

### Relevant debug log with api keys and any passwords redacted
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - DEBUG :: MAIN : Current Version [2cdd779cdbff6e1eb185ae685f0428e8b56782ce] - Latest remote version [2cdd779cdbff6e1eb185ae685f0428e8b56782ce] - Install type [git]
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - INFO :: MAIN : Starting LazyLibrarian on port: 5299, webroot ""
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - INFO :: MAIN : Starting LazyLibrarian web server on http://0.0.0.0:5299/
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - DEBUG :: MAIN : Start processDir job
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - DEBUG :: MAIN : Start checkForUpdates job
Jan 28 17:44:10 raspberrypi python[12160]: 28-Jan-2017 17:44:10 - INFO :: DB_UPGRADE : Image cache updated
Jan 28 17:44:11 raspberrypi python[12160]: 28-Jan-2017 17:44:11 - INFO :: DB_UPGRADE : Database updated to version 12
Jan 28 17:45:08 raspberrypi python[12160]: 28-Jan-2017 17:45:07 - WARNING :: CP Server Thread-4 : Database Error: database is locked
Jan 28 17:45:09 raspberrypi python[12160]: 28-Jan-2017 17:45:09 - WARNING :: CP Server Thread-4 : Database Error: database is locked
Jan 28 17:45:10 raspberrypi python[12160]: 28-Jan-2017 17:45:10 - WARNING :: CP Server Thread-4 : Database Error: database is locked
Jan 28 17:45:11 raspberrypi python[12160]: 28-Jan-2017 17:45:11 - WARNING :: CP Server Thread-4 : Database Error: database is locked
Jan 28 17:45:13 raspberrypi python[12160]: 28-Jan-2017 17:45:12 - WARNING :: CP Server Thread-4 : Database Error: database is locked
Jan 28 17:45:34 raspberrypi python[12160]: 28-Jan-2017 17:45:34 - WARNING :: CP Server Thread-3 : Database Error: database is locked

**Comment by philborman** [comment]
Unable to reproduce it here. Maybe a timing issue, as the database upgrade
happens in a different task to the main loop?

New version due out shortly has a few changes to the upgrade code, would be
interesting to know if that fixes it on your system too.  I'm developing on
a laptop, but my main server is a raspberry pi 3 running osmc, so it should
work. I always run a fresh install as one of the tests before release and
it didn't show up as a problem. Timing issues are difficult to track down.

Maybe I could stop the main loop executing until the upgrade has finished?
Not sure how to do that yet. Still learning :-)

**Comment by TommyE123** [comment]
Hi,
I've tested this on Linux Mint 18.1 on my laptop and it doesnt have the problem at all. It only appears to happen on Raspbian on my pi I use for dev work which is a Raspberry Pi 2. I'm wondering if its a speed issue but lets try your new code and see if that sorts it out!

Thanks
Tom

**Comment by philborman** [comment]
Will push a new version shortly with a _possible_ fix. I think I have found the problem, but as I couldn't reproduce it here I can't be sure!

**Comment by philborman** [comment]
I think this is fixed now, problem was (I think) the background search tasks starting before the database upgrade was complete. Would be good to know if it's working on a pi2 now. If so I will close this ticket.
Thanks.

**Comment by TommyE123** [comment]
Hi Phil, 

Sorry for not getting back to you sooner. I quickly gave it a test this morning before work and unfortunately I have bad news in that the problem still remains. I've posted the latest log here: http://pastebin.com/wf6BbXW7
I removed the current install and reinstalled leaving it for 5mins before I even opened the webpage. I was straight away presented with: 

**Upgrading database, please wait
Updating database to version 13, current version is 0**

Then trying to click on any of the tabs other than logs hangs the page. If you then manage to get back to logs its filled with database locked.

I currently maintain https://github.com/htpcBeginner/AtoMiC-ToolKit which installs your application that I must say is one of the cleanest installs we do thanks to the quality of your code. At the moment I’ve just inserted a Stop, Sleep 20, Start after the install. This clears the issue which in its self isn’t a big deal however it’s a shame that it probably only applies to a small number of systems.

I will do some more tests on this as I have a Pi zero and Pi 3 as well and will try a complete fresh install of Raspbian.

Thanks for looking into this
Tom

**Comment by philborman** [comment]
Well, that's frustrating. I really thought I'd found it.
Interesting that a 20 second pause gets around the problem, where have you put your " Stop, Sleep 20, Start " code, so I can look what's being stopped, is it in lazylibrarian itself, or in your lazylibrarian installation code?

From the log you sent it looks like the database upgrade completed before the external tasks were started, so the only thing running should be the main loop, the webserver, and the scheduler. The scheduler doesn't use the database, so that just leaves 2 candidates.

The first "database is locked" error comes from CP Server Thread-11 which doesn't help us much. I tried to make sure all threads were named but must have missed one (or more) but the Attempted db query: SELECT * from wanted WHERE Status != 'Skipped' and Status != 'Ignored'  can only come from the webserver "history" page. Nothing else uses that query, and the error doesn't appear in the log until 6 minutes after the dbupgrade completes so I guess that's you manually trying to wake up the web interface. Looks to me like the database is locked by something that didn't exit cleanly, but can't see what.

I have a pi3 as I mentioned before. I will try slugging it's clock speed to see if I can get it to fail. If I can reproduce the problem I should be able to fix it.

On a fresh install the database upgrades should be pretty much instant, can't see why even a slow machine would have a problem. We did have a wierd problem with PRAGMA not working on some sqlite3 versions, and there is a PRAGMA call near the end of the dbupgrade routine. Wonder what happens if you comment that out? The database will keep trying to upgrade at each boot thinking it's out of date, but does it affect the lock?  If so there are other ways of storing the database version.

**Comment by TommyE123** [comment]
The "Stop, Sleep 20, Start" code is in the installation script after the initial start of the systemd\init.d script. So not in any of the Lazy Librarian code. With regards to the History page its because its probably the only tab i tried to click on this time however im pretty sure it happens on others as well. Yes the 6 mins was just me leaving it before trying the page. Not sure if this helps much!

Tom

**Comment by philborman** [comment]
Just confirms that I'm understanding the process properly.
I found a few tips on internet searches that might help. I'm running a new
version of the database upgrade code on my git version if you want to give
it a try. It's significantly faster, which might help, and it avoids
calling the database library directly, does everything through a small set
of lazylibrarian subroutines which use thread locking to prevent collisions
between threads.

If you want to try it, the new version is at
https://github.com/philborman/LazyLibrarian.git

**Comment by TommyE123** [comment]
Good news! I've tested this a few times now and it appears to be fixed by the improvements you've made :-)

**Comment by philborman** [comment]
Excellent, thanks for your help. 
I will close the issue now.

Another big update in a few days, good chance to test it again ;-)
