### ISSUE TITLE
Author's Name Ending with Jr. incorrectly added from Calibre db

### ISSUE THREAD

**Issue by Hydro-guy** [DobyTang/LazyLibrarian#639]
L. E. Modesitt, Jr. gets added to LL as Jr., L. E. Modesitt by a Library Scan.  Books found are not added - either to the author as Jr. Modesitt or if author is manually added to LL (appears as a separate author - correctly handled with correct author list) .  

Book searches of NZB.su using api fail as well - although a manual search indicates nzb's are available.

Calibre appears to use an "_" as the period after (Jr_) in its own database.

partial Library Search from log
[D:\XXXX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Recluce Tales (726)
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Recluce Tales] [epub]
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Recluce Tales] []
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : Fuzz failed [Jr., L. E. Modesitt - Recluce Tales] ratio [0,], partial [0,], partname [0,]
09-Feb-2017 15:01:37 - DEBUG   :: LIBRARYSYNC : Fuzz failed [L. E. Modesitt, Jr_ - Recluce Tales] ratio [0,], partial [0,], partname [0,]
09-Feb-2017 15:01:37 - WARNING :: LIBRARYSYNC : Failed to match book [Recluce Tales] by [Jr., L. E. Modesitt] in database

Log from search
Status set to "Wanted" for "Heritage of Cyador"
09-Feb-2017 14:16:04 - INFO :: SEARCHNZB : NZB Searching for 1 book
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : Using stored capabilities for http://api.nzb.su
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [IterateOverNewzNabSites] - http://api.nzb.su
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] searchType [book] with Host [http://api.nzb.su] mode [nzb] using api [xx] for item [{'bookSub': u'(The Saga of Recluce, #18)', 'searchterm': u'L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)', 'bookName': u'Heritage of Cyador', 'authorName': u'L.E. Modesitt Jr.', 'bookid': u'20518867'}]
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'author': u'Modesitt Jr.', 'apikey': u'xx', 't': u'book', 'cat': u'7000,7020', 'title': u'Heritage of Cyador'}
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] URL = http://api.nzb.su/api?author=Modesitt+Jr.&apikey=xx&t=book&cat=7000%2C7020&title=Heritage+of+Cyador
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : Parsing results from <a href="http://api.nzb.su/api?author=Modesitt+Jr.&apikey=xx&t=book&cat=7000%2C7020&title=Heritage+of+Cyador">http://api.nzb.su</a>
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : Found 0 nzb at http://api.nzb.su for: L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : No nzb's found for [L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)] using searchtype book

09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [IterateOverNewzNabSites] - http://api.nzb.su
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] searchType [general] with Host [http://api.nzb.su] mode [nzb] using api [xx] for item [{'bookSub': u'(The Saga of Recluce, #18)', 'searchterm': u'L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)', 'bookName': u'Heritage of Cyador', 'authorName': u'L.E. Modesitt Jr.', 'bookid': u'20518867'}]
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'q': u'L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)', 'apikey': u'xx', 't': u'search', 'extended': u'1'}
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : [NewzNabPlus] URL = http://api.nzb.su/api?q=L.E.+Modesitt+Jr.+Heritage+of+Cyador%3A+%28The+Saga+of+Recluce%2C+%2318%29&apikey=xx&t=search&extended=1
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : Parsing results from <a href="http://api.nzb.su/api?q=L.E.+Modesitt+Jr.+Heritage+of+Cyador%3A+%28The+Saga+of+Recluce%2C+%2318%29&apikey=xx&t=search&extended=1">http://api.nzb.su</a>
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : Found 0 nzb at http://api.nzb.su for: L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)
09-Feb-2017 14:16:04 - DEBUG :: SEARCHNZB : No nzb's found for [L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)] using searchtype general
09-Feb-2017 14:16:04 - INFO :: SEARCHNZB : NZB Searches for L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18) returned no results.
09-Feb-2017 14:16:04 - INFO :: SEARCHNZB : NZBSearch for Wanted items complete, found 0 books

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: 378d49406f47831cc0a64a699b88693e1c076d51
Windows10 default git

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Interesting. Haven't tried an author with Jr.  on the end. Tried importing as a new author by searching for L. E. Modesitt Jr. in the search box and it works ok.  The books are cross referenced to the author using the goodreads id rather than the name so they appear in the library correctly.  I guess the problem you hit is that we are not collecting the right data from calibre,  or maybe from the book metadata?  
The nzb.su problem is that we shouldn't include the period in the url,  at least that part is easy to fix.  
I am away for a few days but will look into it after the weekend -  unless anyone else gets there first!

**Comment by Hydro-guy** [comment]
The calibre library seems to change the trailing dot into an _ and uses that to indicate how it handles a JR. name.  I tried to indicate that in the github submission – looked ok before I pressed submit but seemed to strip it out of the submission.

 

Many thanks – this is a very interesting project.  

 

John

**Comment by philborman** [comment]
Ok, just pushed a new version which should fix the problem with Jr. on the end. Hopefully I didn't break anything in the process.  Would be good if you could try it and report back, seems to work here. To try this, go to the Modesitt author page in your current version of lazylibrarian and select "Remove Author", this will remove him from LL database but won't remove any files!  Now upgrade LL from the Config page (Check version, click Update on the popup window), and then go back to the main Authors page and run LibraryScan to re-import him into the library. Thanks.

**Comment by Hydro-guy** [comment]
Seems to still show up as Jr., L. E. Modesitt  after library search while if added through Title/Author/ISBN shows as a separate author.  Log shows books as rejected “invalid language” but Calibre itself under metadata says lang of books I have is “English”  Was 12 commits behind before upgrade – 6 after.

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: a6e1e6f5041184418374c94ccaeb1d9da23ac3a8 : Latest Version: not checked

 

 

 

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Recluce Tales (726)

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Recluce Tales] [epub]

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Recluce Tales] []

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 14:08:27 - INFO :: LIBRARYSYNC : Adding new author [Jr., L. E. Modesitt]

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : Now adding new author: Jr., L. E. Modesitt to database

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : Searching for author with name: Jr., L. E. Modesitt

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%2C%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : getAuthorImage: Returning Cached response for C:\lazylibrarian\cache\13868129.jpg

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : [Jr., L. E. Modesitt] Now processing books with GoodReads API

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : url http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : author name Jr., L. E. Modesitt

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : LibraryThing reports language [invalid] for

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 14:08:27 - DEBUG :: LIBRARYSYNC : Skipped Saga of Recluce: Year 1-415 with language Unknown

11-Feb-2017 14:08:28 - DEBUG :: LIBRARYSYNC : LibraryThing reports language [invalid] for

11-Feb-2017 14:08:28 - DEBUG :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:28 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:28 - DEBUG :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 14:08:28 - DEBUG :: LIBRARYSYNC : Skipped Assassin's Price with language Unknown

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : LibraryThing reports language [invalid] for

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Skipped The Imager Portfolio: Volume I: Imager, Imager's Challenge and Imager's Intrigue with language Unknown

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q&page=2

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Found 3 total books for author

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Removed 3 unwanted language results for author

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Removed 0 bad character or no-name results for author

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Removed 0 duplicate results for author

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Found 0 books by author marked as Ignored

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Imported/Updated 0 books for author

11-Feb-2017 14:08:29 - INFO :: LIBRARYSYNC : [Jr., L. E. Modesitt] Book processing complete: Added 0 books to the database

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : [Jr., L. E. Modesitt] Author update complete

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Fuzz failed [Jr., L. E. Modesitt - Recluce Tales] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Fuzz failed [L. E. Modesitt, Jr. - Recluce Tales] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 14:08:29 - WARNING :: LIBRARYSYNC : Failed to match book [Recluce Tales] by [Jr., L. E. Modesitt] in database

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library Now scanning subdirectory \L. E. Modesitt, Jr_\Treachery's Tools (728)

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Treachery's Tools] [epub]

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Treachery's Tools] []

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Fuzz failed [Jr., L. E. Modesitt - Treacherys Tools] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 14:08:29 - DEBUG :: LIBRARYSYNC : Fuzz failed [L. E. Modesitt, Jr. - Treacherys Tools] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 14:08:29 - WARNING :: LIBRARYSYNC : Failed to match book [Treacherys Tools] by [Jr., L. E. Modesitt] in database

**Comment by philborman** [comment]
Not sure why you are showing as 6 commits behind, but it looks like you are still running an old version. Try switching to your git directory and running "git pull"

I think the unknown language might be down to using cached results, might need to empty the xml cache?

**Comment by Hydro-guy** [comment]
Sorta new at git – but – updating from LL get both “7 commits behind” and “already up to date” when process completes.  Suggestions as to my stupidity welcome….

 

John

 

11-Feb-2017 17:05:46 - DEBUG :: WEBSERVER : Set Install Type, Current & Latest Version and Commit status

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\lazylibrarian

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (RunGit)Git output: [master]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (getCurrentGitBranch) Current local branch of repo is [master]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (getInstallType) [git] install detected. Setting Branch to [master]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (RunGit)Trying to execute: "git rev-parse HEAD" with shell in C:\lazylibrarian

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (RunGit)Git output: [73658effddd64673d0c641b57b6d2c546836a538]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (updateVersionFile) Updating [C:\lazylibrarian\version.txt] with value [73658effddd64673d0c641b57b6d2c546836a538]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (getCurrentVersion) - Install type [git] Local Version is set to [73658effddd64673d0c641b57b6d2c546836a538]

11-Feb-2017 17:05:47 - DEBUG :: WEBSERVER : (getLatestVersion_FromGit) Retrieving latest version information from github command=[https://api.github.com/repos/dobytang/lazylibrarian/commits/master]

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : (getLatestVersion_FromGit) Branch [master] Latest Version has been set to [a0d9a555f091822e16eec63043cc305383cdac6f]

11-Feb-2017 17:05:48 - INFO :: WEBSERVER : [VersionCheck] -  Comparing currently installed version with latest github version

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : (getCommitDifferenceFromGit) -  Check for differences between local & repo by [https://api.github.com/repos/dobytang/LazyLibrarian/compare/73658effddd64673d0c641b57b6d2c546836a538...a0d9a555f091822e16eec63043cc305383cdac6f]

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : JSONDecode url

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : pull total_commits from json object

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : (getCommitDifferenceFromGit) -  GitHub reports as follows Status [ahead] - Ahead [7] - Behind [0] - Total Commits [7]

11-Feb-2017 17:05:48 - INFO :: WEBSERVER : [VersionCheck] -  New version is available. You are 7 commits behind

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : (getCommitDifferenceFromGit) - exiting with commit value of [7]

11-Feb-2017 17:05:48 - DEBUG :: WEBSERVER : Update check complete

11-Feb-2017 17:05:59 - DEBUG :: CP Server Thread-11 : (webServe-Update) - Performing update

11-Feb-2017 17:06:09 - INFO :: MAIN : LazyLibrarian is updating...

INFO:lazylibrarian:MAIN : LazyLibrarian is updating...

11-Feb-2017 17:06:09 - DEBUG :: MAIN : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\lazylibrarian

DEBUG:lazylibrarian:MAIN : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in C:\lazylibrarian

11-Feb-2017 17:06:09 - DEBUG :: MAIN : (RunGit)Git output: [master]

DEBUG:lazylibrarian:MAIN : (RunGit)Git output: [master]

11-Feb-2017 17:06:09 - DEBUG :: MAIN : (getCurrentGitBranch) Current local branch of repo is [master]

DEBUG:lazylibrarian:MAIN : (getCurrentGitBranch) Current local branch of repo is [master]

11-Feb-2017 17:06:09 - DEBUG :: MAIN : (RunGit)Trying to execute: "git stash clear" with shell in C:\lazylibrarian

DEBUG:lazylibrarian:MAIN : (RunGit)Trying to execute: "git stash clear" with shell in C:\lazylibrarian

11-Feb-2017 17:06:10 - DEBUG :: MAIN : (RunGit)Git output: []

DEBUG:lazylibrarian:MAIN : (RunGit)Git output: []

11-Feb-2017 17:06:10 - DEBUG :: MAIN : (RunGit)Trying to execute: "git pull origin master" with shell in C:\lazylibrarian

DEBUG:lazylibrarian:MAIN : (RunGit)Trying to execute: "git pull origin master" with shell in C:\lazylibrarian

11-Feb-2017 17:06:11 - DEBUG :: MAIN : (RunGit)Git output: [From https://github.com/philborman/LazyLibrarian

* branch            master     -> FETCH_HEAD

Already up-to-date.]

DEBUG:lazylibrarian:MAIN : (RunGit)Git output: [From https://github.com/philborman/LazyLibrarian

* branch            master     -> FETCH_HEAD

Already up-to-date.]

11-Feb-2017 17:06:11 - INFO :: MAIN : (update) No update available, not updating

INFO:lazylibrarian:MAIN : (update) No update available, not updating

11-Feb-2017 17:06:11 - INFO :: MAIN : (update) Output: From https://github.com/philborman/LazyLibrarian

* branch            master     -> FETCH_HEAD

Already up-to-date.

 

INFO:lazylibrarian:MAIN : (update) Output: From https://github.com/philborman/LazyLibrarian

* branch            master     -> FETCH_HEAD

Already up-to-date.

**Comment by philborman** [comment]
Looks like your local version is 73658effddd64673d0c641b57b6d2c546836a538
Latest dobytang git version is a0d9a555f091822e16eec63043cc305383cdac6f
<https://api.github.com/repos/dobytang/LazyLibrarian/compare/73658effddd64673d0c641b57b6d2c546836a538...a0d9a555f091822e16eec63043cc305383cdac6f>
you are 7 versions behind, and then the update fails but says you are now
up to date???

I think a reinstall is the best way forward, but don't know why it's
failed. Any local changes that might block a git upgrade?
Usually git will complain if that's the case, but nothing in the logs to
show why. git stash clear is something I don't usually see?
If your config.ini and lazylibrarian.db are in a user folder (rather than
in lazylibrarian root) you can safely delete the lazylibrarian install
directory and your user data is safe.

**Comment by Hydro-guy** [comment]
Totally erased root folder and reinstalled – only kept .ini file. 

 

Used command  “git clone https://github.com/DobyTang/LazyLibrarian.git c:\LazyLibrarian”

LL shows as up to date when checked through Update. 

Repo: https://github.com/dobytang/lazylibrarian : Branch: master
Current Version: a0d9a555f091822e16eec63043cc305383cdac6f : Latest Version: a0d9a555f091822e16eec63043cc305383cdac6f

 

 

Re-scanned db from Calibre via Library Scan – L. E. Modesitt Jr.  still added from my library as Jr., Modesitt and the two books in library are not added to his available books.  Goodreads does not find any books either because of this.  Calibre shows books normally in its database.

 



 

If I add Modesitt manually to LL it finds him and his books online correctly – but not the ones in my library.

 

 

 

[D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Recluce Tales (726)

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Recluce Tales] [epub]

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Recluce Tales] []

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 19:46:39 - INFO    :: LIBRARYSYNC : Adding new author [Jr., L. E. Modesitt]

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : Now adding new author: Jr., L. E. Modesitt to database

11-Feb-2017 19:46:39 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr., L. E. Modesitt

11-Feb-2017 19:46:40 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/api/author_url/Jr.%2C%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:40 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:40 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : Cached google image for Jr., L. E. Modesitt

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Now processing books with GoodReads API

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : url http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : author name Jr., L. E. Modesitt

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

11-Feb-2017 19:46:41 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : Skipped The Imager Portfolio: Volume I: Imager, Imager's Challenge and Imager's Intrigue with language Unknown

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 19:46:42 - DEBUG   :: LIBRARYSYNC : Skipped Saga of Recluce: Year 1-415 with language Unknown

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Skipped Assassin's Price with language Unknown

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : CacheHandler: Storing XML for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q&page=2

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Found 3 total books for author

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Removed 3 unwanted language results for author

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Removed 0 bad character or no-name results for author

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Removed 0 duplicate results for author

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Found 0 books by author marked as Ignored

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Imported/Updated 0 books for author

11-Feb-2017 19:46:44 - INFO    :: LIBRARYSYNC : [Jr., L. E. Modesitt] Book processing complete: Added 0 books to the database

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Author update complete

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Fuzz failed [Jr., L. E. Modesitt - Recluce Tales] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Fuzz failed [L. E. Modesitt, Jr. - Recluce Tales] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 19:46:44 - WARNING :: LIBRARYSYNC : Failed to match book [Recluce Tales] by [Jr., L. E. Modesitt] in database

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Treachery's Tools (728)

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Treachery's Tools] [epub]

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Treachery's Tools] []

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Fuzz failed [Jr., L. E. Modesitt - Treacherys Tools] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 19:46:44 - DEBUG   :: LIBRARYSYNC : Fuzz failed [L. E. Modesitt, Jr. - Treacherys Tools] ratio [0,], partial [0,], partname [0,]

11-Feb-2017 19:46:44 - WARNING :: LIBRARYSYNC : Failed to match book [Treacherys Tools] by [Jr., L. E. Modesitt] in database

**Comment by Hydro-guy** [comment]
Tried removing unknown languages from Calibre db – mass setting all metadata to English.  No difference.

 

Tried to download another book by modesitt  (manually added author) to download via LL – still does not find although epub exists on NZB.su – albeit as L E Modesit Jr without the ”.”  ending – or the . after the initials.

 

LL still seems to be passing the “.” in the search string.

 

 

 

 

11-Feb-2017 21:48:09 - DEBUG :: SEARCHNZB : [NewzNabPlus] - nzb Search parameters set to {'q': u'L.E. Modesitt Jr. Madness in Solidar: (Imager Portfolio, #9)', 'apikey': u'XX', 't': u'search', 'extended': u'1'}

11-Feb-2017 21:48:09 - DEBUG :: SEARCHNZB : [NewzNabPlus] URL = http://api.nzb.su/api?q=L.E.+Modesitt+Jr.+Madness+in+Solidar%3A+%28Imager+Portfolio%2C+%239%29&apikey=XX&t=search&extended=1

11-Feb-2017 21:48:09 - DEBUG :: SEARCHNZB : Parsing results from <a href="http://api.nzb.su/api?q=L.E.+Modesitt+Jr.+Madness+in+Solidar%3A+%28Imager+Portfolio%2C+%239%29&apikey=XX&t=search&extended=1">http://api.nzb.su</a>

11-Feb-2017 21:48:09 - DEBUG :: SEARCHNZB : Found 0 nzb at http://api.nzb.su for: L.E. Modesitt Jr. Madness in Solidar: (Imager Portfolio, #9)

11-Feb-2017 21:48:09 - DEBUG :: SEARCHNZB : No nzb's found for [L.E. Modesitt Jr. Madness in Solidar: (Imager Portfolio, #9)] using searchtype general

11-Feb-2017 21:48:09 - INFO :: SEARCHNZB : NZB Searches for L.E. Modesitt Jr. Madness in Solidar: (Imager Portfolio, #9) returned no results.

11-Feb-2017 21:48:09 - INFO :: SEARCHNZB : NZBSearch for Wanted items complete, found 0 books

**Comment by philborman** [comment]
Found the problem, seems goodreads has the same issue with Jr. as lazylibrarian.
This is the output from 
http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

<author>
<id>13868129</id>
<name>Jr., L. E. Modesitt</name>
<link>
<![CDATA[
https://www.goodreads.com/author/show/13868129.Jr_L_E_Modesitt
]]>
</link>

That's where we pick up the wrong data, just need to figure out what to do about it...

**Comment by philborman** [comment]
Ok, an update. Hopefully the goodreads name issue is fixed now, still working on nzb.su
Seems it's not as simple as a punctuation issue. They don't like search terms to include short words or initials or the book series. Problem is by stripping everything out we might break other providers, so I might have to do an extra search if the original one returns no results...
Original search, no results  L.E. Modesitt Jr. Heritage of Cyador: (The Saga of Recluce, #18)
Stripping punctuation, no results L E Modesitt Jr Heritage of Cyador The Saga of Recluce 18
Stripping authorname to surname only, no results Modesitt Heritage of Cyador The Saga of Recluce 18
Stripping bookname to title only, RESULT   Modesitt Heritage of Cyador

**Comment by Hydro-guy** [comment]
Interesting – a manual search of nzb.su using the string “L. E. Modesitt, Jr.” returns 120 results – adding “heritage of cyador” to previous string returns 3 results.

I wonder why the api is so restricted – the manual entry is obviously doing a fuzzy search.

**Comment by philborman** [comment]
Similar results here with the api. just "Modesitt" returning over 100
results and "Modesitt Heritage of Cyador" returning 3

Maybe the manual search processes the string before searching, but the api
expects the string to be pre-processed? Many of the nzb providers are based
on the same software, I will see if I can get some documentation on how the
search works.

**Comment by Hydro-guy** [comment]
Updated LL to latest version this am – still encountering the issue with using library scan to add that miserable author ….

 

Repo: https://github.com/dobytang/lazylibrarian : Branch: master

Current Version: 9971f8d69e79304ad15480f8456ff66b0e6d6b9c : Latest Version: 9971f8d69e79304ad15480f8456ff66b0e6d6b9c

 

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Recluce Tales (726)

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Recluce Tales] [epub]

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Recluce Tales] []

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Formatted authorname [L. E. Modesitt, Jr.] to [Jr. L. E. Modesitt]

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Author Jr. L. E. Modesitt not found in database, trying to add

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

16-Feb-2017 07:38:31 - INFO    :: LIBRARYSYNC : Adding new author [Jr., L. E. Modesitt]

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Now adding new author: Jr., L. E. Modesitt to database

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr., L. E. Modesitt

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%2C%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : getAuthorImage: Returning Cached response for C:\lazylibrarian\cache\13868129.jpg

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Now processing books with GoodReads API

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : url http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : author name Jr., L. E. Modesitt

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=34182432&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

16-Feb-2017 07:38:31 - DEBUG   :: LIBRARYSYNC : Skipped The Imager Portfolio: Volume I: Imager, Imager's Challenge and Imager's Intrigue with language Unknown

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=32868681&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Skipped Saga of Recluce: Year 1-415 with language Unknown

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : LibraryThing reports language [invalid] for 

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Book URL: http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=33865022&key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : GR language: Unknown

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Skipped Assassin's Price with language Unknown

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/list/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q&page=2

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Found 3 total books for author

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Removed 3 unwanted language results for author

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Removed 0 bad character or no-name results for author

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Removed 0 duplicate results for author

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Found 0 books by author marked as Ignored

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Imported/Updated 0 books for author

16-Feb-2017 07:38:33 - INFO    :: LIBRARYSYNC : [Jr., L. E. Modesitt] Book processing complete: Added 0 books to the database

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Author update complete

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : No books found in database for Jr., L. E. Modesitt

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : No books found in database for L. E. Modesitt, Jr.

16-Feb-2017 07:38:33 - WARNING :: LIBRARYSYNC : Failed to match book [Recluce Tales] by [Jr., L. E. Modesitt] in database

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Treachery's Tools (728)

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Treachery's Tools] [epub]

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Treachery's Tools] []

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Formatted authorname [L. E. Modesitt, Jr.] to [Jr. L. E. Modesitt]

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Author Jr. L. E. Modesitt not found in database, trying to add

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Jr. L. E. Modesitt

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Jr.%20L.%20E.%20Modesitt?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/13868129.xml?key=ckvsiSDsuqh7omh74ZZ6Q

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : [Jr., L. E. Modesitt] Processing info for authorID: 13868129

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : Found goodreads authorname Jr., L. E. Modesitt in database

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : No books found in database for Jr., L. E. Modesitt

16-Feb-2017 07:38:33 - DEBUG   :: LIBRARYSYNC : No books found in database for L. E. Modesitt, Jr.

16-Feb-2017 07:38:33 - WARNING :: LIBRARYSYNC : Failed to match book [Treacherys Tools] by [Jr., L. E. Modesitt] in database

**Comment by philborman** [comment]
Ah, silly bug in the last release. I fixed it here but haven't pushed the
fix yet as it's quite trivial. Working on some other bits and will push a
fix with the next release.

If you want to try the fix, in providers.py line 471, if
words[1].strip().strip('.').lower() in lazylibrarian.NAME_POSTFIX
Your version is missing () at the end of .lower
Basically takes the ", Jr." part, converts it to "jr", finds "jr" in
NAME_POSTFIX and knows to keep it at the end of the name

**Comment by Hydro-guy** [comment]
Hmm – think maybe your providers.py is a bit ahead of mine – I get a blank line at line 471 using vim.  The only instance of NAME_POSTFIX using FIND occurs in line 47 (co-incidence?)   if len(word) > 1 and word.lower() not in lazylibrarian.NAME_POSTFIX                           Could very well be my inexperience with vim and searching/editing .py files – I’ll wait for the commit. 

 

From line 464 onwards:

    if params:

        logger.debug('[NewzNabPlus] - %s Search parameters set to %s' % (searchMode, str(params)))

    else:

        logger.debug('[NewzNabPlus] - %s No matching search parameters' % searchMode)

 

    return params

 

 

def ReturnResultsFieldsBySearchType(book=None, nzbdetails=None, host=None, searchMode=None):

    """

    # searchType has multiple query params for t=, which return different results sets.

    # books have a dedicated check, so will use that.

    # mags don't so will have more generic search term.

    # http://newznab.readthedocs.org/en/latest/misc/api/#predefined-categorie

**Comment by philborman** [comment]
Oops,  my bad. Librarysync,  not providers.
I have pushed the fix now.

**Comment by Hydro-guy** [comment]
Updated – and – new and interesting behaviour.  Multiple authors is causing issue that cascaded into the post_fix fix.

 

[D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \Kelly Eileen Hake,Cathy Marie Hake,\The Brides of Chance Collection (720)

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : book meta [978-1-62836-249-7] [eng] [Kelly Eileen Hake,Cathy Marie Hake,Tracey V. Bateman] [The Brides of Chance Collection] [epub]

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : file meta [978-1-62836-249-7] [eng] [Kelly Eileen Hake,Cathy Marie Hake,Tracey V. Bateman] [The Brides of Chance Collection] []

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Found Language [eng] ISBN [978-1-62836-249-7]

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Already cached Lang [eng] ISBN [-1-]

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Formatted authorname [Kelly Eileen Hake,Cathy Marie Hake,Tracey V. Bateman] to [Cathy Marie Hake Kelly Eileen Hake]

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Author Cathy Marie Hake Kelly Eileen Hake not found in database, trying to add

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Cathy Marie Hake Kelly Eileen Hake

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Cathy%20Marie%20Hake%20Kelly%20Eileen%20Hake?key=ckvsiSDsuqh7omh74ZZ6Q

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/author/show/82603.xml?key=ckvsiSDsuqh7omh74ZZ6Q

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : [Cathy Marie Hake] Processing info for authorID: 82603

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Failed to match author [Cathy Marie Hake Kelly Eileen Hake] to authorname [Cathy Marie Hake] fuzz [64]

17-Feb-2017 07:21:28 - DEBUG   :: LIBRARYSYNC : Failed to match author [Cathy Marie Hake Kelly Eileen Hake] in database

 

Caused issue here.

 

7-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Recluce Tales (726)

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Recluce Tales] [epub]

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Recluce Tales] []

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Formatted authorname [L. E. Modesitt, Jr.] to [Cathy Marie Hake Jr.]

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Author Cathy Marie Hake Jr. not found in database, trying to add

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Cathy Marie Hake Jr.

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Cathy%20Marie%20Hake%20Jr.?key=ckvsiSDsuqh7omh74ZZ6Q

17-Feb-2017 07:21:29 - WARNING :: LIBRARYSYNC : No authors found with name: Cathy Marie Hake Jr.

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Failed to match author [Cathy Marie Hake Jr.] in database

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library] Now scanning subdirectory \L. E. Modesitt, Jr_\Treachery's Tools (728)

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : book meta [] [en-US] [L. E. Modesitt, Jr.] [Treachery's Tools] [epub]

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : file meta [] [eng] [L. E. Modesitt, Jr.] [Treachery's Tools] []

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Formatted authorname [L. E. Modesitt, Jr.] to [Cathy Marie Hake Jr.]

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Author Cathy Marie Hake Jr. not found in database, trying to add

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Searching for author with name: Cathy Marie Hake Jr.

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : CacheHandler: Returning CACHED response for http://www.goodreads.com/api/author_url/Cathy%20Marie%20Hake%20Jr.?key=ckvsiSDsuqh7omh74ZZ6Q

17-Feb-2017 07:21:29 - WARNING :: LIBRARYSYNC : No authors found with name: Cathy Marie Hake Jr.

17-Feb-2017 07:21:29 - DEBUG   :: LIBRARYSYNC : Failed to match author [Cathy Marie Hake Jr.] in database

**Comment by philborman** [comment]
Well that's interesting.
Seems the multiple commas in the previous multi-author book are carrying over into the next search.
I will add protection against multiple commas in the next version. Fairly major update coming up, completely rewritten the config section and it needs more testing before release.

**Comment by Hydro-guy** [comment]
Looking forward to next update!!

 

Another inconsistency on the library scan adding books to LL  - a manual search of  Goodreads finds this book “Hold Her Heart” by Holly Jacobs (http://www.goodreads.com/book/show/31623161-hold-her-heart) – but doesn’t show in LL under available books even when in library.  Admittedly Goodreads doesn’t have the ISBN that the metadata carries – only the ASIN code.  Librarything does have it under the ISBN10 though.  Guessing that the lack of an ISBN13 on either Goodreads or Librarything prevents Active Author Scan from adding book to LL library??  To answer my own question – seems that unknown language by goodreads/Librarything was the killer – even if book meta in library indicates that language is English.

 

Hmm – might prioritize library meta over goodreads/libthing response if titles match??

 

Without updating metadata in Calibre:

 

18-Feb-2017 14:26:36 - DEBUG   :: SCANAUTHOR : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library\Holly Jacobs] Now scanning subdirectory \Hold Her Heart (748)

18-Feb-2017 14:26:36 - DEBUG   :: SCANAUTHOR : book meta [] [en] [Holly Jacobs] [Hold Her Heart (Words of the Heart)] [epub]

18-Feb-2017 14:26:36 - DEBUG   :: SCANAUTHOR : File meta incomplete in 

18-Feb-2017 14:26:36 - DEBUG   :: SCANAUTHOR : Fuzz failed [Holly Jacobs - Hold Her Heart (Words of the Heart)] ratio [46,Do You Hear What I Hear?], partial [63,Carry Her Heart], partname [69,Carry Her Heart]

18-Feb-2017 14:26:36 - WARNING :: SCANAUTHOR : Failed to match book [Hold Her Heart (Words of the Heart)] by [Holly Jacobs] in database

 

After updating metadata in Calibre:

 

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : [D:\XX\Documents\Ebooks\Calibre Library\Calibre Library\Holly Jacobs] Now scanning subdirectory \Hold Her Heart (748)

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : book meta [] [en] [Holly Jacobs] [Hold Her Heart (Words of the Heart)] [epub]

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : file meta [9780578183893] [eng] [Holly Jacobs] [Hold Her Heart] []

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : Found Language [eng] ISBN [9780578183893]

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : Already cached Lang [eng] ISBN [057]

18-Feb-2017 15:54:36 - DEBUG   :: SCANAUTHOR : Fuzz failed [Holly Jacobs - Hold Her Heart] ratio [69,Carry Her Heart], partial [71,Carry Her Heart], partname [0,]

18-Feb-2017 15:54:36 - WARNING :: SCANAUTHOR : Failed to match book [Hold Her Heart] by [Holly Jacobs] in database

 

Is it because language identified by goodreads (although correctly identifying book) is unknown?

 

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : LibraryThing reports language [invalid] for 

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : Book URL: http://www.goodreads.com/book/show?id=31623161&key=ckvsiSDsuqh7omh74ZZ6Q

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : CacheHandler: Returning CACHED response for http://www.goodreads.com/book/show?id=31623161&key=ckvsiSDsuqh7omh74ZZ6Q

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : GR language: Unknown

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : Skipped Hold Her Heart with language Unknown

18-Feb-2017 16:56:06 - DEBUG   :: REFRESHAUTHOR : ISBN978 returned eng for 037

**Comment by philborman** [comment]
Problem is the "unknown" language. When we ask goodreads/googlebooks for a list of an authors books, we only add ones into lazylibrarians library that match your configured languages. Some authors are _very_ widely translated. "Agatha Christie" for example pulls in about 1800 books in at least a dozen languages, only one of which I can read, so about 1600 will be results I have to wade through that I don't want.

Couple of options
Option 1:  
1. Make sure in Config->Processing  the "Search when added" box is NOT ticked
2. Search for Holly Jacobs using the top right search box. 
3. Click the "Add Book" button next to "Hold Her Heart". This will add the book into lazylibrarians database. We don't stop it being loaded as you particularly said you want to add it. There might be a warning printed in the log, not sure. If you left the "Search when added" box ticked, lazylibrarian will now start to search for a copy to download, which you don't want as you already have a copy.
4. Go to Holly Jacobs page in the author list
5. Click Library Scan. This should notice the book is there and mark it as available.

Option 2:
1. Add "unknown" into your Config->Importing Import languages
2. Go to Holly Jacobs page in the author list
3. Click Refresh Author. This should rescan the list from goodreads and include any books with unknown language. Wait for the rescan to complete (completion message in log). 
5. Click Library Scan. This should notice the book is there and mark it as available.
6. Remove "unknown" from your config list

Option 3:
-- NOT IMPLEMENTED YET --
There may be an online tool or lookup service that we can use to convert asin to isbn so we can get a language that way. isbn often contains language info, asin doesn't. Ideally we would like a free converter that we can talk to with json or simple html calls. I will need to look into this.

**Comment by philborman** [comment]
Just pushed the new version.
Haven't found a usable asin to isbn converter yet.

That particular book is a good example of the problem though. Librarything has it, but the workpage has no ISBNs and no language either.
https://www.librarything.com/api/whatwork.php?title=Hold+Her+Heart+/+by+Holly+Jacobs

**Comment by Hydro-guy** [comment]
Thank you for the explanation on how to manually add title – I understand that it would cause as significant increase in size and unwieldiness to db. if all of the possible titles of every author were added – even if they were not displayed.  

 

Wondering if a last ditch author check (individual title - that author) in Library Scan would be useful if the calibre db. metadata indicated that the book language was known?

**Comment by philborman** [comment]
It's too late in the import process, I think.
At the time we scan a new author into the database we have no idea what
books might be found in calibre or lazylibrarian databases, and the time
overhead of  looking in both databases for every book with language
"unknown" is too large. I don't think it's worth the effort, just ignore
unknown ones, or load them in with unknown language. Also the same with an
external lookup service. I did some tests on my library of 200 or so
authors, and found over 10,000 books in goodreads that didn't make it into
my lazylibrarian database. At 1 second per book that would add almost 3
hours to the libraryscan process. ( most api services,
goodreads/librarything etc  limit you to 1 call per second )

**Comment by Hydro-guy** [comment]
My lack of knowledge of how the the goodreads/librarything search api’s work is the problem.  I was thinking that you could just ignore the language issue (given that the book is in your library) and match the title with a single api call.    

 

I suppose you could assign a probability that all books in same calibre subdirectory were by the same author if one book existed in LL db – but that’s getting too complicated – better to keep things simple.

**Comment by philborman** [comment]
Maybe when the book is found in the libraryscan, if the author is in the
library but the book is not, rescan the author with "unknown" temporarily
added to the language list. If that succeeds, use the language from the
book metadata. I will have a look at that as an option.

On Sun, 19 Feb 2017 at 20:05 Hydro-guy <notifications@github.com> wrote:

My lack of knowledge of how the the goodreads/librarything search api’s
work is the problem. I was thinking that you could just ignore the language
issue (given that the book is in your library) and match the title with a
single api call.



I suppose you could assign a probability that all books in same calibre
subdirectory were by the same author if one book existed in LL db – but
that’s getting too complicated – better to keep things simple.

**Comment by philborman** [comment]
Ok  just to update the last thought,  rescanning for the book ignoring
language preferences seems to be working.  It's only an issue with
goodreads,  googlebooks sometimes tells you the book is "en" rather than
"unknown" but if the book is not found on googlebooks it really is not
there.  No point in asking them again.

Just a bit more testing before updating the github branch.

**Comment by Hydro-guy** [comment]
All right – L.E. Modesitt Jr.  added correctly  and you ran Holly Jacobs to earth!! :)  

 

21-Feb-2017 16:30:12 - INFO    :: LIBRARYSYNC : 82/261 new/modified books found and added to the database

21-Feb-2017 16:30:12 - INFO    :: LIBRARYSYNC : 2324 files processed

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : No missing WorkPages

21-Feb-2017 16:30:12 - WARNING :: LIBRARYSYNC : Found 59 books in your library with unknown language

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : GoodReads was hit 0 times for books

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : GoodReads was hit 0 times for languages

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : LibraryThing was hit 0 times for languages

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Language cache was hit 0 times

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Unwanted language removed 0 books

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Unwanted characters removed 0 books

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Unable to cache language for 0 books with missing ISBN

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Found 0 duplicate books

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Rescan 15 hits, 28 miss

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Cache 93 hits, 64 miss

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : ISBN Language cache holds 162 entries

21-Feb-2017 16:30:12 - DEBUG   :: LIBRARYSYNC : Updating bookcounts for 54 authors

21-Feb-2017 16:30:13 - INFO    :: LIBRARYSYNC : Library scan complete

**Comment by Hydro-guy** [comment]
Many thanks for your effort – I appreciate the work you put into this.

John

**Comment by philborman** [comment]
No probs.
I will close this issue now.
