### ISSUE TITLE
Cannot setup Pushover notifications

### ISSUE THREAD

**Issue by Rafkat** [DobyTang/LazyLibrarian#755]
### 
To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted:
27-Apr-2017 13:29:20 - DEBUG   :: CP Server Thread-11 : Pushover: Sending notification This is a test notification from LazyLibrarian
27-Apr-2017 13:29:20 - DEBUG   :: CP Server Thread-11 : Testing Pushover authentication and retrieving the device list.
27-Apr-2017 13:29:20 - DEBUG   :: CP Server Thread-11 : Pushover Response: 400
27-Apr-2017 13:29:20 - DEBUG   :: CP Server Thread-11 : Pushover Reason: Bad Request
27-Apr-2017 13:29:20 - ERROR   :: CP Server Thread-11 : Pushover request failed: Bad Request

Hello!

I'm trying to setup Pushover Notification, but it fails for some reason. I've filled API token and keys from my pushover account. Priority set to 0 (tried 1 as well). Device as per my Pushover account, however device name is being wiped after I hit Save changes button.
The keys/token work fine on SickRage and Couchpotato but not on Lazy.
Would you advise what needs to be done?

Many thanks.

**Comment by Rafkat** [comment]
Update: It seems that switching to the Default Theme is fixing the issue. However when I switch back to Bookstrap it's broken again.

**Comment by philborman** [comment]
ok, there is a bug in the bookstrap config.html file
On line 1470 it is missing name="pushover_device"

I am just in the middle of a fairly large code reorganisation, and can't
easily push a fix as the reorganisation still needs more testing,  but you
could edit your bookstrap config.html file with a text editor and put
name="pushover_device"
 just after it says id="pushover_device"

Probably won't get a new version released for a day or two.

**Comment by Rafkat** [comment]
Thank you, @philborman 
I'll wait for the release as I don't want to dig and modify something in the docker image.

**Comment by philborman** [comment]
Should be fixed in latest version

**Comment by Rafkat** [comment]
Thanks @philborman.
I've updated to the latest version, however, if Bookstrap theme is used, the Pushover notifications are still not working. Though, it's working perfectly fine with the default theme.

**Comment by philborman** [comment]
Latest version as of 30 minutes ago, version should start 925f ?

**Comment by Rafkat** [comment]
925f4c583bdfe87d6f33af323d20d05e6ff1c863

**Comment by philborman** [comment]
ok, slightly different problem. Seems somehow your "series" table has an
entry where author is None. Shouldn't happen. Probably a result of the
earlier failed upgrades. I will add some code to filter the bad data out.
Shouldn't take long.

**Comment by Rafkat** [comment]
Device is now being saved. But Pushover API is wiped out, though I can't understand the pattern when this happens. 
When I click on test it fails as before.
Np, I can test it again once you push changes.

**Comment by philborman** [comment]
ok, think I've found the api problem, and added extra debugging which might help if it's still not working

**Comment by Rafkat** [comment]
Updated to the latest. All works fine now. Thanks, @philborman
